piro13_quiz/urls.py
from django.contrib import admin
from django.urls import path, include
import goologin.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', goologin.views.login, name="login"),
    path('accounts/', include('allauth.urls')),
    path('quiz/', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    # 일단 test 가 메인 페이지
    path('', views.test),
    path('quiz/create/', views.quiz_create),
    path('quiz/quiz_list/', views.quiz_list),
    path('<int:pk>/delete/', views.delete_view, name='delete_view'),
    path('<int:pk>/solve/', views.solve_quiz, name='solve_quiz'),
    path('quiz/quiz_rank/', views.quiz_rank, name='quiz_rank'),

]

goologin/models.py
from django.db import models

class Blog(models.Model):
    text = models.TextField()

quiz/models.py
from django.db import models
from django.forms.widgets import RadioSelect
from goologin import adapter

class Item(models.Model):
    CHOICES1 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')]
    CHOICES2 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')]
    CHOICES3 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')]
    CHOICES4 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')]
    CHOICES5 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')]

    madeby = models.CharField(max_length=30, null=True)

    # 퀴즈 제목
    title = models.CharField(max_length=30, blank=True)
    # 퀴즈 5개 문제 정의 (~~~는? 영역)
    Q1 = models.CharField(max_length=60, blank=False)
    Q2 = models.CharField(max_length=60, blank=False)
    Q3 = models.CharField(max_length=60, blank=False)
    Q4 = models.CharField(max_length=60, blank=False)
    Q5 = models.CharField(max_length=60, blank=False)
    # 그냥 넣어야 할 거 같아서 넣었어..
    Q1pic = models.CharField(choices=CHOICES1, max_length=2, blank=False)
    Q2pic = models.CharField(choices=CHOICES2, max_length=2, blank=False)
    Q3pic = models.CharField(choices=CHOICES3, max_length=2, blank=False)
    Q4pic = models.CharField(choices=CHOICES4, max_length=2, blank=False)
    Q5pic = models.CharField(choices=CHOICES5, max_length=2, blank=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 퀴즈 제목 뽑아내기
    # def __str__(self):
    #     return self.title, self.madeby

    #  1차 마이그레이트


class Answer(models.Model):
    CHOICES1 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'),
                ('4', '아리랑'), ('5', '아리랑')]
    CHOICES2 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'),
                ('4', '아리랑'), ('5', '아리랑')]
    CHOICES3 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'),
                ('4', '아리랑'), ('5', '아리랑')]
    CHOICES4 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'),
                ('4', '아리랑'), ('5', '아리랑')]
    CHOICES5 = [('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'),
                ('4', '아리랑'), ('5', '아리랑')]

    item = models.ForeignKey(Item, related_name="answers", on_delete=models.CASCADE, null=True)
    madeby = models.CharField(max_length=30, null=True)

    Q1ans = models.CharField(choices=CHOICES1, max_length=2, blank=False)
    Q2ans = models.CharField(choices=CHOICES2, max_length=2, blank=False)
    Q3ans = models.CharField(choices=CHOICES3, max_length=2, blank=False)
    Q4ans = models.CharField(choices=CHOICES4, max_length=2, blank=False)
    Q5ans = models.CharField(choices=CHOICES5, max_length=2, blank=False)

quiz/forms.py
from django import forms
from .models import Item
from .models import Answer


class QuizForm(forms.ModelForm):
    # 각 문제에 라디오 버튼 생성,
    #  모델폼 기능 구현을 위해 메타 클래스 생성 러브레터 참고자료에 모델 폼 있음
    class Meta:
        model = Item
        fields = '__all__'
        widgets = {
            'Q1pic': forms.RadioSelect,
            'Q2pic': forms.RadioSelect,
            'Q3pic': forms.RadioSelect,
            'Q4pic': forms.RadioSelect,
            'Q5pic': forms.RadioSelect,
        },


class AnswerForm(forms.ModelForm):
    # 각 문제에 라디오 버튼 생성,
    #  모델폼 기능 구현을 위해 메타 클래스 생성 러브레터 참고자료에 모델 폼 있음
    class Meta:
        model = Answer
        fields = '__all__'
        widgets = {
            'madeby': forms.CharField,
            'Q1ans': forms.RadioSelect,
            'Q2ans': forms.RadioSelect,
            'Q3ans': forms.RadioSelect,
            'Q4ans': forms.RadioSelect,
            'Q5ans': forms.RadioSelect,
        },

goologin/views.py
from django.shortcuts import render

def login(request):
    return render(request, 'goologin/login.html')

quiz/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Item, Answer
from .forms import QuizForm, AnswerForm


def test(request):
    return render(request, 'quiz/test.html')


def quiz_create(request, item=None):
    quizs = Item.objects.all()
    if request.method == 'POST':
        form = QuizForm(request.POST)
        if form.is_valid():
            item = form.save()
            return render(request, 'quiz/quiz_list.html', {'quizs': quizs})

    else:
        form = QuizForm()
    return render(request, 'quiz/item_form.html', {
        'form': form,
    })


def quiz_list(request):
    quizs = Item.objects.all()
    return render(request, 'quiz/quiz_list.html', {'quizs': quizs})


def delete_view(request, pk):
    context = {}
    quiz = Item.objects.get(pk=pk)
    quiz.delete()

    return render(request, 'quiz/delete_view.html', context)


def answer_quiz(request):
    quiz = Answer.objects.all()
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            item = form.save()
            return render(request, 'quiz/quiz_list.html', {'quiz': quiz})
    else:
        form = AnswerForm()
    return render(request, 'quiz/item_form.html', {
        'form': form,
    })


def solve_quiz(request, pk):
    quiz = Item.objects.get(pk=pk)
    answers = Answer.objects.all()
    if (request.method == 'POST'):
        form = AnswerForm(request.POST)
        if form.is_valid():
            item = form.save()
            return render(request, 'quiz/quiz_list.html', {'answers': answers, 'quiz':quiz})
    else:
        form = AnswerForm()
    return render(request, 'quiz/solve_quiz.html', {'form': form, 'quiz':quiz})


def quiz_rank(request):
    return render(request, 'quiz/quiz_rank.html')

goologin/templates/goologin/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}

{% block login %}
<div>
    {% if user.is_authenticated %}
    <a href="/accounts/logout">로그아웃</a>
    <a href="/quiz/quiz/quiz_rank">내퀴즈보기</a>
    {{ user.username }} 님이 로그인중
    {% else %}
    <a href="{% provider_login_url 'google' %}">구글 로그인</a><br/>
    {% endif %}
</div>
{% endblock %}
{% block content %}
<div id="context">
    <h1>나를 가장 잘 아는</h1>
    <h1>피로그래머는 누구일까요?!</h1>
    <div id="quizbtn">
        {% if user.is_authenticated %}
        <a href="quiz/quiz/create/">퀴즈내러가기</a>
        <a href="quiz/quiz/quiz_list">퀴즈맞추러가기</a>
        {% else %}
        <a href="">퀴즈맞추러가기</a><br/>
        {% endif %}
    </div>
</div>
{% endblock %}

quiz/templates/quiz/delete_view.html
{% extends 'goologin/login.html' %}

{% block content %}
<form method="POST">
    <!-- Security token by Django -->
    {% csrf_token %}
    <h1>정말 지우시겠습니까?</h1>
    <input type="button" value="Yes" onclick='location.href="/"'>
    <a href="/">Cancel </a>
</form>
{% endblock %}

quiz/templates/quiz/item_form.html
{% extends 'goologin/login.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            list-style: none;
        }

        /* 라디오 버튼 가로축으로 늘어놓기 */
        form ul > li {
            display: inline-flex;
        }

        /* 퀴즈 마다 아래쪽 수평선  */
        tr {
            border-bottom: 5px solid rebeccapurple;
        }

    </style>
</head>
{% block content %}
<body>

    <h1 class="menu_title">퀴즈 생성하기</h1>

    <P>|출제자:<!--{{유저아이디}}--></P>
    <hr>

    <form action="" method="post">
        {% csrf_token %}
        Title: {{ form.title }} <br><br>
        Username: {{ form.madeby }} <br><br>
        <!-- 1번 문제  -->
        Q1: {{form.Q1}} <br>
        {{form.Q1pic}}
        <hr>
        <!-- 2번 문제  -->
        Q2: {{form.Q2}} <br>
        {{form.Q2pic}}
        <hr>
        <!-- 3번 문제  -->
        Q3: {{form.Q3}} <br>
        {{form.Q3pic}}
        <hr>
        <!-- 4번 문제  -->
        Q4: {{form.Q4}} <br>
        {{form.Q4pic}}
        <hr>
        <!-- 5번 문제  -->
        Q5: {{form.Q5}} <br>
        {{form.Q5pic}}
        <hr>
        <br/>
        <input id="submit_btn" type="submit">
    </form>

</body>
{% endblock %}
</html>

quiz/templates/quiz/quiz_list.html
{% extends 'goologin/login.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            list-style: none;
        }

        form ul > li {
            display: inline-flex;
        }

        tr {
            border-bottom: 5px solid rebeccapurple;
        }

    </style>
</head>
{% block content %}
<body>
<div id="context">
    <h1>퀴즈 리스트</h1>
    <p>현재 플레이어의 등록된 퀴즈를 보여주는 페이지 입니다.</p>
    <p>아무말 아무말 아무말 아무말 아무말 아무말 아무말 아무말 아무말</p>

    <h4>현재 사용자: {{ user.username }}</h4>
    {% for quiz in quizs %}
    <div id="quiz">
        <div class="title">
            <br/><br/>
            <p>제목: {{ quiz.title }}</p>

        </div>
        <div class="inline">
            <p>출제자: {{ quiz.madeby }}</p>

        </div>
        {% if quiz.madeby == user.username %}
        <a href="{% url 'quiz:delete_view' quiz.pk%}">퀴즈 삭제</a>
        {% else %}
        <a href="{% url 'quiz:solve_quiz' quiz.pk%}">퀴즈 풀기</a>
        {% endif %}
        <div class="inline">

        </div>

    </div>
    {% endfor %}
</div>
</body>
{% endblock %}

</html>

quiz/templates/quiz/quiz_rank.html
{% extends 'goologin/login.html' %}

{% block content %}
{% for answer in item.answers.all %}
    <div>{{answer.madeby}}</div>

{% endfor %}
{% endblock %}

quiz/templates/quiz/solve_quiz.html
{% extends 'goologin/login.html' %}

{% block content%}
<body>
<div>제목:{{ quiz.title }}</div>
<div>
    출제자: {{ quiz.madeby }}<br/><br/>

    문제 번호: {{ quiz.pk }}

    <form action="" method="post">
        {% csrf_token %}
        푸는사람: {{form.madeby}}<br/>
        <!-- 1번 문제  -->
        Q1: {{quiz.Q1}} <br>
        {{form.Q1ans}}
        <hr>
        <!-- 2번 문제  -->
        Q2: {{quiz.Q2}} <br>
        {{form.Q2ans}}
        <hr>
        <!-- 3번 문제  -->
        Q3: {{quiz.Q3}} <br>
        {{form.Q3ans}}
        <hr>
        <!-- 4번 문제  -->
        Q4: {{quiz.Q4}} <br>
        {{form.Q4ans}}
        <hr>
        <!-- 5번 문제  -->
        Q5: {{quiz.Q5}} <br>
        {{form.Q5ans}}
        <hr>
        <br/>
        <input id="submit_btn" type="submit">
    </form>


</div>
</body>
{% endblock %}

quiz/templates/quiz/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROGRAM QUIZ</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        #nav {
            width: 100%;
            height: 70px;
            background-color: black;
            float: left;
        }

        #nav h3 {
            color: pink;
            padding: 20px 0 0 50px;
            float: left;
        }

        #nav div {
            float: right;
            color: white;
            padding: 10px;
        }

        #nav a {
            text-decoration: none;
            color: white;
            padding: 5px;

        }

        #body {
            background-color: #222222;
            width: 100%;
            height: 100%;

        }

        #footer {
            background-color: black;
            width: 100%;
            height: 70px;
        }

        #footer h6 {
            color: gray;
            margin: 0 auto;
            width: 350px;

        }

        #footer h5 {
            width: 300px;
            color: gray;
            margin: 0 auto;
            padding: 10px;
        }

        #body h1 {
            color: white;
            margin: 0 auto;
            width: 450px;
            text-align: center;
        }

        #body a {
            text-decoration: None;
            color: pink;
            border: 2px solid pink;
            border-radius: 10px;
            padding: 10px;
        }

        #quizbtn {
            margin: 0 auto;
            height: 100px;
            width: 300px;
            padding: 50px;
        }

        #body {
            color: white;
        }
        #context{
            height: 650px;
        }

        #quiz a{
            float: right;
            margin-right:
        }


    </style>
</head>
<body>
<div id="nav">
    <a href="/"><h3>PROGRAM QUIZ</h3></a>
    {% block login %}

    {% endblock %}
</div>

<div id="body">

    {% block content %}


    {% endblock %}
</div>
<div id="footer">
    <h5>피로그래밍 13기 | 박소민 손민주 오채은 이지호</h5>
    <h6>서울특별시 관악구 관악로 1, 서울대학교 벤처경영 교육 및 연구 동아리</h6>
</div>
</body>
</html>